import asyncio
import os
import json
import shutil
import random
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from jinja2 import Environment, FileSystemLoader

# Import SITE_URL from config
from config import MONGO_URI, DB_NAME, COLLECTION_NAME, SITE_URL, POSTS_PER_PAGE, CATEGORIES

# --- Configuration ---
SITE_DIR = "site"
POSTS_DIR = os.path.join(SITE_DIR, "posts")
THUMBNAIL_DIR = os.path.join(SITE_DIR, "thumbnails")
STATIC_DIR = os.path.join(SITE_DIR, "static")
TEMPLATE_DIR = "templates"

# --- Custom Jinja2 Filter ---
def nl2br_filter(text):
    """Converts newlines in text to HTML <br> tags."""
    return text.replace('\n', '<br>')

# --- Template Setup ---
def setup_templates():
    os.makedirs(TEMPLATE_DIR, exist_ok=True)
    
    # Base Template (with Search link)
    with open(os.path.join(TEMPLATE_DIR, "base.html"), "w", encoding="utf-8") as f:
        f.write('''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ seo.title }}</title>
    <meta name="description" content="{{ seo.description }}">
    <link rel="canonical" href="{{ seo.canonical_url }}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ seo.canonical_url }}">
    <meta property="og:title" content="{{ seo.title }}">
    <meta property="og:description" content="{{ seo.description }}">
    <meta property="og:image" content="{{ seo.image_url }}">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="{{ seo.canonical_url }}">
    <meta property="twitter:title" content="{{ seo.title }}">
    <meta property="twitter:description" content="{{ seo.description }}">
    <meta property="twitter:image" content="{{ seo.image_url }}">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
    <link rel="stylesheet" href="/static/style.css">
</head>
<body>
    <div class="container">
        <header class="site-header">
            <h1><a href="/" style="text-decoration: none; color: inherit;">Adult Posting</a></h1>
            <nav>
                <a href="/">Home</a>
                <a href="/search.html">Advanced Search</a>
                <div class="category-nav">
                    <span>Categories:</span>
                    {% for category in categories %}
                    <a href="/search.html?category={{ category }}">{{ category }}</a>
                    {% endfor %}
                </div>
            </nav>
        </header>
        <main>
            {% block content %}{% endblock %}
        </main>
        <footer class="site-footer">
            <p>Generated by AI &copy; {{ now.year }}</p>
        </footer>
    </div>
    {% block scripts %}{% endblock %}
</body>
</html>''')

    # Homepage Template
    with open(os.path.join(TEMPLATE_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write('''{% extends "base.html" %}
{% block content %}
<div class="post-grid">
    {% for post in posts %}
    <article class="post-card">
        <a href="{{ post.page_url }}">
            {% if post.thumbnail_url %}
            <img src="{{ post.thumbnail_url }}" alt="{{ post.title }}" class="post-thumbnail" loading="lazy">
            {% endif %}
            <div class="post-content">
                <h3 class="post-title">{{ post.title }}</h3>
                <p class="post-meta">Uploaded on {{ post.human_date }}</p>
                {% if post.category %}
                <span class="category-badge">{{ post.category }}</span>
                {% endif %}
            </div>
        </a>
    </article>
    {% endfor %}
</div>
{% if pagination %}
<div class="pagination">
    {% if pagination.has_prev %}
    <a href="{{ pagination.prev_page_url }}" class="pagination-link">&laquo; Previous</a>
    {% endif %}
    {% for page in pagination.page_urls %}
    {% if page.is_current %}
    <span class="pagination-current">{{ page.number }}</span>
    {% else %}
    <a href="{{ page.url }}" class="pagination-link">{{ page.number }}</a>
    {% endif %}
    {% endfor %}
    {% if pagination.has_next %}
    <a href="{{ pagination.next_page_url }}" class="pagination-link">Next &raquo;</a>
    {% endif %}
</div>
{% endif %}
{% endblock %}''')
        
    # Post Detail Template
    with open(os.path.join(TEMPLATE_DIR, "post.html"), "w", encoding="utf-8") as f:
        f.write('''{% extends "base.html" %}
{% block content %}
<article>
    <header>
        <h1>{{ post.title }}</h1>
        <p><small>Uploaded on {{ post.human_date }}{% if post.duration %} | Duration: {{ post.duration }}{% endif %}</small></p>
    </header>
    {% if post.thumbnail_url %}
    <img src="{{ post.thumbnail_url }}" alt="Thumbnail for {{ post.title }}" style="width: 100%; max-width: 600px; height: auto; border-radius: 8px; margin-bottom: 2rem;">
    {% endif %}

    <p>{{ post.description | nl2br }}</p>

    <a href="{{ post.telegram_link }}" role="button" class="contrast" target="_blank" rel="noopener noreferrer">Get File</a>
</article>

{% if suggested_posts %}
<section style="margin-top: 3rem;">
    <h2>You Might Also Like</h2>
    <div class="suggested-posts-grid">
        {% for s_post in suggested_posts %}
        <article class="post-card">
            <a href="{{ s_post.page_url }}">
                {% if s_post.thumbnail_url %}
                <img src="{{ s_post.thumbnail_url }}" alt="{{ s_post.title }}" class="post-thumbnail" loading="lazy">
                {% endif %}
                <div class="post-content">
                    <h3 class="post-title">{{ s_post.title }}</h3>
                </div>
            </a>
        </article>
        {% endfor %}
    </div>
</section>
{% endif %}
{% endblock %}''')

    # Search Page Template
    with open(os.path.join(TEMPLATE_DIR, "search.html"), "w", encoding="utf-8") as f:
        f.write('''{% extends "base.html" %}
{% block content %}
<h2>Advanced Search</h2>
<div class="search-filters">
    <input type="search" id="search-input" placeholder="Search by title or description..." style="width: 100%; padding: 12px; font-size: 1rem; margin-bottom: 1rem;">
    <select id="category-select">
        <option value="">All Categories</option>
        {% for category in categories %}
        <option value="{{ category }}">{{ category }}</option>
        {% endfor %}
    </select>
    <input type="date" id="date-from" placeholder="From date">
    <input type="date" id="date-to" placeholder="To date">
    <button id="search-button" class="contrast">Search</button>
</div>
<div id="search-results" class="post-grid"></div>
<div id="loading" style="text-align: center; margin: 2rem 0; display: none;">
    <p>Loading...</p>
</div>
{% endblock %}
{% block scripts %}
<script src="/static/search.js"></script>
{% endblock %}''')

# --- Site Generation Logic ---

def generate_robots_txt():
    content = f"User-agent: *\nAllow: /\n\nSitemap: {SITE_URL}/sitemap.xml"
    with open(os.path.join(SITE_DIR, "robots.txt"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_sitemap(posts):
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR))
    template_str = """<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>{{ site_url }}</loc>
        <lastmod>{{ now_iso }}</lastmod>
        <priority>1.00</priority>
    </url>
    {% for post in posts %}
    <url>
        <loc>{{ post.absolute_url }}</loc>
        <lastmod>{{ post.iso_date }}</lastmod>
        <priority>0.80</priority>
    </url>
    {% endfor %}
</urlset>"""
    template = env.from_string(template_str)
    
    sitemap_posts = []
    for post in posts:
        sitemap_posts.append({
            'absolute_url': f"{SITE_URL}{post['page_url']}",
            'iso_date': post['iso_date']
        })
        
    sitemap_xml = template.render(
    site_url=SITE_URL,
    posts=sitemap_posts,
    now_iso=datetime.now(timezone.utc).isoformat()
)
    with open(os.path.join(SITE_DIR, "sitemap.xml"), "w", encoding="utf-8") as f:
        f.write(sitemap_xml)

async def generate_site():
    print("Starting website generation with search features...")
    
    # 0. Setup Jinja2 Templates & Environment
    setup_templates()
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), autoescape=True)
    env.filters['nl2br'] = nl2br_filter
    index_template = env.get_template("index.html")
    post_template = env.get_template("post.html")
    search_template = env.get_template("search.html")
    
    # 1. Prepare directories
    os.makedirs(SITE_DIR, exist_ok=True)
    
    if os.path.exists(POSTS_DIR):
        shutil.rmtree(POSTS_DIR)
    
    os.makedirs(POSTS_DIR)
    os.makedirs(THUMBNAIL_DIR, exist_ok=True)
    # Copy only necessary static files
    shutil.copy(os.path.join("static", "style.css"), STATIC_DIR)
    shutil.copy(os.path.join("static", "search.js"), STATIC_DIR)

    # 2. Fetch data from MongoDB
    client = AsyncIOMotorClient(MONGO_URI)
    db = client[DB_NAME]
    collection = db[COLLECTION_NAME]
    
    query = {'url': {'$exists': True}, 'title': {'$exists': True}, 'telegram_link': {'$exists': True}}
    posts_cursor = collection.find(query)
    posts = await posts_cursor.to_list(length=None)

    # Filter posts to only include those with upload_date <= now
    now = datetime.now(timezone.utc)
    filtered_posts = []
    for post in posts:
        upload_date = post.get('upload_date')
        dt_object = None
        if isinstance(upload_date, datetime):
            dt_object = upload_date
        elif isinstance(upload_date, str):
            try:
                dt_object = datetime.fromisoformat(upload_date.replace('Z', '+00:00'))
            except ValueError:
                try:
                    dt_object = datetime.strptime(upload_date, '%Y-%m-%d').replace(tzinfo=timezone.utc)
                except (ValueError, TypeError):
                    pass
        if dt_object is None:
            processed_at_ts = post.get('processed_at')
            dt_object = datetime.fromtimestamp(processed_at_ts, tz=timezone.utc) if processed_at_ts else datetime.now(timezone.utc)

        # Ensure dt_object is timezone-aware before comparison
        if dt_object.tzinfo is None:
            dt_object = dt_object.replace(tzinfo=timezone.utc)

        if dt_object <= now:
            filtered_posts.append(post)

    posts = filtered_posts
    def get_sort_key(post):
        upload_date = post.get('upload_date')
        if isinstance(upload_date, datetime):
            if upload_date.tzinfo is None:
                return upload_date.replace(tzinfo=timezone.utc)
            return upload_date
        processed_at = post.get('processed_at', 0)
        return datetime.fromtimestamp(processed_at, tz=timezone.utc)
    posts.sort(key=get_sort_key, reverse=True)
    
    print(f"Found {len(posts)} posts to generate.")

    processed_posts = []
    for post in posts:
        post_id = str(post['_id'])
        page_url = f"/posts/{post_id}.html"
        
        thumbnail_url = "/static/placeholder.png"
        original_thumb_path = post.get('thumbnail_local_path')
        if original_thumb_path and os.path.exists(original_thumb_path):
            try:
                thumb_filename = os.path.basename(original_thumb_path)
                dest_thumb_path = os.path.join(THUMBNAIL_DIR, thumb_filename)
                shutil.copy(original_thumb_path, dest_thumb_path)
                thumbnail_url = f"/thumbnails/{thumb_filename}"
            except FileNotFoundError:
                print(f"Warning: Thumbnail not found for post {post_id} at {original_thumb_path}")
        
        absolute_thumbnail_url = f"{SITE_URL}{thumbnail_url}"

        upload_date = post.get('upload_date')
        dt_object = None
        if isinstance(upload_date, datetime):
            dt_object = upload_date
        elif isinstance(upload_date, str):
            try:
                # Handle ISO format with 'T' separator and optional 'Z'
                dt_object = datetime.fromisoformat(upload_date.replace('Z', '+00:00'))
            except ValueError:
                try:
                    # Fallback for date only
                    dt_object = datetime.strptime(upload_date, '%Y-%m-%d')
                except (ValueError, TypeError):
                    pass # Keep dt_object as None
        
        if dt_object is None:
            processed_at_ts = post.get('processed_at')
            dt_object = datetime.fromtimestamp(processed_at_ts, tz=timezone.utc) if processed_at_ts else datetime.now(timezone.utc)

        human_date = dt_object.strftime('%B %d, %Y')
        iso_date = dt_object.isoformat()

        processed_post_data = {
            'title': post.get('title', 'No Title'),
            'description': post.get('description', 'No description available.'),
            'telegram_link': post.get('telegram_link', '#'),
            'human_date': human_date,
            'iso_date': iso_date,
            'thumbnail_url': thumbnail_url,
            'page_url': page_url,
            'absolute_thumbnail_url': absolute_thumbnail_url,
            'category': post.get('category', 'Uncategorized'),
            'duration': post.get('duration', '')
        }
        processed_posts.append(processed_post_data)

        # Get 20 random posts for suggestion (excluding the current post)
        other_posts = [p for p in posts if str(p['_id']) != post_id]
        random.shuffle(other_posts)
        suggested_posts = other_posts[:20]

        # Format suggested posts for the template
        suggested_posts_data = []
        for s_post in suggested_posts:
            s_post_id = str(s_post['_id'])
            s_page_url = f"/posts/{s_post_id}.html"
            
            s_thumbnail_url = "/static/placeholder.png"
            s_original_thumb_path = s_post.get('thumbnail_local_path')
            if s_original_thumb_path and os.path.exists(s_original_thumb_path):
                try:
                    s_thumb_filename = os.path.basename(s_original_thumb_path)
                    s_dest_thumb_path = os.path.join(THUMBNAIL_DIR, s_thumb_filename)
                    shutil.copy(s_original_thumb_path, s_dest_thumb_path) # Ensure thumbnail is copied
                    s_thumbnail_url = f"/thumbnails/{s_thumb_filename}"
                except FileNotFoundError:
                    print(f"Warning: Thumbnail not found for suggested post {s_post_id} at {s_original_thumb_path}")
            
            suggested_posts_data.append({
                'title': s_post.get('title', 'No Title'),
                'page_url': s_page_url,
                'thumbnail_url': s_thumbnail_url
            })

        seo_data = {
            'title': f"{processed_post_data['title']} | My Awesome Site",
            'description': processed_post_data['description'][:160],
            'canonical_url': f"{SITE_URL}{page_url}",
            'image_url': absolute_thumbnail_url
        }
        post_html = post_template.render(
            seo=seo_data,
            post=processed_post_data,
            now=datetime.now(timezone.utc),
            suggested_posts=suggested_posts_data, # Pass suggested posts
            categories=CATEGORIES
        )
        with open(os.path.join(POSTS_DIR, f"{post_id}.html"), "w", encoding="utf-8") as f:
            f.write(post_html)

    # 5. Generate paginated homepages
    total_posts = len(posts)
    total_pages = (total_posts + POSTS_PER_PAGE - 1) // POSTS_PER_PAGE

    for page_num in range(1, total_pages + 1):
        start_index = (page_num - 1) * POSTS_PER_PAGE
        end_index = start_index + POSTS_PER_PAGE
        current_page_posts = posts[start_index:end_index]

        # Prepare pagination context
        pagination = {
            'current_page': page_num,
            'total_pages': total_pages,
            'has_prev': page_num > 1,
            'has_next': page_num < total_pages,
            'prev_page_url': f"/{'index' if page_num - 1 == 1 else f'page{page_num - 1}'}.html" if page_num > 1 else None,
            'next_page_url': f"/page{page_num + 1}.html" if page_num < total_pages else None,
            'page_urls': [{
                'number': p,
                'url': f"/{'index' if p == 1 else f'page{p}'}.html",
                'is_current': p == page_num
            } for p in range(1, total_pages + 1)]
        }

        # SEO for the current page
        homepage_seo = {
            'title': f"Homepage {'- Page ' + str(page_num) if page_num > 1 else ''} | My Awesome Site",
            'description': "The best place to find awesome content.",
            'canonical_url': f"{SITE_URL}/{'index' if page_num == 1 else f'page{page_num}'}.html",
            'image_url': f"{SITE_URL}/static/default-social-image.png"
        }
        
        output_filename = "index.html" if page_num == 1 else f"page{page_num}.html"
        output_path = os.path.join(SITE_DIR, output_filename)

        page_html = index_template.render(
            seo=homepage_seo,
            now=datetime.now(timezone.utc),
            posts=current_page_posts,
            pagination=pagination,
            categories=CATEGORIES
        )
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(page_html)

    # 6. Generate Search page
    search_seo = {'title': "Advanced Search | Adult Posting", 'description': "Advanced search for adult content with filters.", 'canonical_url': f"{SITE_URL}/search.html", 'image_url': f"{SITE_URL}/static/default-social-image.png"}
    search_html = search_template.render(seo=search_seo, now=datetime.now(timezone.utc), categories=CATEGORIES)
    with open(os.path.join(SITE_DIR, "search.html"), "w", encoding="utf-8") as f:
        f.write(search_html)

    # 7. Generate supporting files
    generate_robots_txt()
    generate_sitemap(processed_posts)

    # 8. Cleanup template directory
    shutil.rmtree(TEMPLATE_DIR)

    print("Website generation complete with search features!")


if __name__ == '__main__':
    try:
        import jinja2
    except ImportError:
        print("Jinja2 not found. Installing...")
        import subprocess
        import sys
        subprocess.check_call([sys.executable, "-m", "pip", "install", "jinja2"])

    asyncio.run(generate_site())
