import asyncio
import os
import json
import shutil
from datetime import datetime, timezone
from motor.motor_asyncio import AsyncIOMotorClient
from jinja2 import Environment, FileSystemLoader

# Import SITE_URL from config
from config import MONGO_URI, DB_NAME, COLLECTION_NAME, SITE_URL

# --- Configuration ---
SITE_DIR = "site"
POSTS_DIR = os.path.join(SITE_DIR, "posts")
THUMBNAIL_DIR = os.path.join(SITE_DIR, "thumbnails")
STATIC_DIR = os.path.join(SITE_DIR, "static")
TEMPLATE_DIR = "templates"

# --- Custom Jinja2 Filter ---
def nl2br_filter(text):
    """Converts newlines in text to HTML <br> tags."""
    return text.replace('\n', '<br>')

# --- Template Setup ---
def setup_templates():
    os.makedirs(TEMPLATE_DIR, exist_ok=True)
    
    # Base Template (with Search link)
    with open(os.path.join(TEMPLATE_DIR, "base.html"), "w", encoding="utf-8") as f:
        f.write('''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ seo.title }}</title>
    <meta name="description" content="{{ seo.description }}">
    <link rel="canonical" href="{{ seo.canonical_url }}">

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website">
    <meta property="og:url" content="{{ seo.canonical_url }}">
    <meta property="og:title" content="{{ seo.title }}">
    <meta property="og:description" content="{{ seo.description }}">
    <meta property="og:image" content="{{ seo.image_url }}">

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image">
    <meta property="twitter:url" content="{{ seo.canonical_url }}">
    <meta property="twitter:title" content="{{ seo.title }}">
    <meta property="twitter:description" content="{{ seo.description }}">
    <meta property="twitter:image" content="{{ seo.image_url }}">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
    <link rel="stylesheet" href="/static/style.css">
</head>
<body>
    <div class="container">
        <header class="site-header">
            <h1><a href="/" style="text-decoration: none; color: inherit;">Adult Posting</a></h1>
            <nav>
                <a href="/">Home</a>
                <a href="/search.html">Search</a>
            </nav>
        </header>
        <main>
            {% block content %}{% endblock %}
        </main>
        <footer class="site-footer">
            <p>Generated by Gemini AI &copy; {{ now.year }}</p>
        </footer>
    </div>
    {% block scripts %}{% endblock %}
</body>
</html>''')

    # Homepage Template
    with open(os.path.join(TEMPLATE_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write('''{% extends "base.html" %}
{% block content %}
<div id="post-grid-container" class="post-grid">
    <!-- Posts will be loaded here by JavaScript -->
</div>
<div id="loading" style="text-align: center; margin: 2rem 0; display: none;">
    <p>Loading more posts...</p>
</div>
{% endblock %}
{% block scripts %}
<script src="/static/app.js"></script>
{% endblock %}''')
        
    # Post Detail Template
    with open(os.path.join(TEMPLATE_DIR, "post.html"), "w", encoding="utf-8") as f:
        f.write('''{% extends "base.html" %}
{% block content %}
<article>
    <header>
        <h1>{{ post.title }}</h1>
        <p><small>Uploaded on {{ post.human_date }}</small></p>
    </header>
    {% if post.thumbnail_url %}
    <img src="{{ post.thumbnail_url }}" alt="Thumbnail for {{ post.title }}" style="width: 100%; max-width: 600px; height: auto; border-radius: 8px; margin-bottom: 2rem;">
    {% endif %}
    
    <p>{{ post.description | nl2br }}</p>
    
    <a href="{{ post.telegram_link }}" role="button" class="contrast" target="_blank" rel="noopener noreferrer">Get File</a>
</article>
{% endblock %}''')

    # Search Page Template
    with open(os.path.join(TEMPLATE_DIR, "search.html"), "w", encoding="utf-8") as f:
        f.write('''{% extends "base.html" %}
{% block content %}
<h2>Search Posts</h2>
<input type="search" id="search-input" placeholder="Type to search..." style="width: 100%; padding: 12px; font-size: 1rem; margin-bottom: 1rem;">
<div id="search-results"></div>
{% endblock %}
{% block scripts %}
<script src="/static/search.js"></script>
{% endblock %}''')

# --- Site Generation Logic ---

def generate_robots_txt():
    content = f"User-agent: *\nAllow: /\n\nSitemap: {SITE_URL}/sitemap.xml"
    with open(os.path.join(SITE_DIR, "robots.txt"), "w", encoding="utf-8") as f:
        f.write(content)

def generate_sitemap(posts):
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR))
    template_str = """<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <url>
        <loc>{{ site_url }}</loc>
        <lastmod>{{ now_iso }}</lastmod>
        <priority>1.00</priority>
    </url>
    {% for post in posts %}
    <url>
        <loc>{{ post.absolute_url }}</loc>
        <lastmod>{{ post.iso_date }}</lastmod>
        <priority>0.80</priority>
    </url>
    {% endfor %}
</urlset>"""
    template = env.from_string(template_str)
    
    sitemap_posts = []
    for post in posts:
        sitemap_posts.append({
            'absolute_url': f"{SITE_URL}{post['page_url']}",
            'iso_date': post['iso_date']
        })
        
    sitemap_xml = template.render(
    site_url=SITE_URL,
    posts=sitemap_posts,
    now_iso=datetime.now(timezone.utc).isoformat()
)
    with open(os.path.join(SITE_DIR, "sitemap.xml"), "w", encoding="utf-8") as f:
        f.write(sitemap_xml)

async def generate_site():
    print("Starting website generation with search features...")
    
    # 0. Setup Jinja2 Templates & Environment
    setup_templates()
    env = Environment(loader=FileSystemLoader(TEMPLATE_DIR), autoescape=True)
    env.filters['nl2br'] = nl2br_filter
    index_template = env.get_template("index.html")
    post_template = env.get_template("post.html")
    search_template = env.get_template("search.html")
    
    # 1. Prepare directories
    os.makedirs(SITE_DIR, exist_ok=True)
    
    if os.path.exists(POSTS_DIR):
        shutil.rmtree(POSTS_DIR)
    
    os.makedirs(POSTS_DIR)
    os.makedirs(THUMBNAIL_DIR, exist_ok=True)
    shutil.copytree("static", STATIC_DIR, dirs_exist_ok=True)

    # 2. Fetch data from MongoDB
    client = AsyncIOMotorClient(MONGO_URI)
    db = client[DB_NAME]
    collection = db[COLLECTION_NAME]
    
    query = {'url': {'$exists': True}, 'title': {'$exists': True}, 'telegram_link': {'$exists': True}}
    posts_cursor = collection.find(query)
    posts = await posts_cursor.to_list(length=None)

    # Filter posts to only include those with upload_date <= now
    now = datetime.now(timezone.utc)
    filtered_posts = []
    for post in posts:
        upload_date = post.get('upload_date')
        dt_object = None
        if isinstance(upload_date, datetime):
            dt_object = upload_date
        elif isinstance(upload_date, str):
            try:
                dt_object = datetime.fromisoformat(upload_date.replace('Z', '+00:00'))
            except ValueError:
                try:
                    dt_object = datetime.strptime(upload_date, '%Y-%m-%d')
                except (ValueError, TypeError):
                    pass
        if dt_object is None:
            processed_at_ts = post.get('processed_at')
            dt_object = datetime.fromtimestamp(processed_at_ts, tz=timezone.utc) if processed_at_ts else datetime.now(timezone.utc)

        if dt_object <= now:
            filtered_posts.append(post)

    posts = filtered_posts
    def get_sort_key(post):
        upload_date = post.get('upload_date')
        if isinstance(upload_date, datetime):
            return upload_date
        processed_at = post.get('processed_at', 0)
        return datetime.fromtimestamp(processed_at, tz=timezone.utc)
    posts.sort(key=get_sort_key, reverse=True)
    
    print(f"Found {len(posts)} posts to generate.")

    processed_posts = []
    for post in posts:
        post_id = str(post['_id'])
        page_url = f"/posts/{post_id}.html"
        
        thumbnail_url = "/static/placeholder.png"
        original_thumb_path = post.get('thumbnail_local_path')
        if original_thumb_path and os.path.exists(original_thumb_path):
            try:
                thumb_filename = os.path.basename(original_thumb_path)
                dest_thumb_path = os.path.join(THUMBNAIL_DIR, thumb_filename)
                shutil.copy(original_thumb_path, dest_thumb_path)
                thumbnail_url = f"/thumbnails/{thumb_filename}"
            except FileNotFoundError:
                print(f"Warning: Thumbnail not found for post {post_id} at {original_thumb_path}")
        
        absolute_thumbnail_url = f"{SITE_URL}{thumbnail_url}"

        upload_date = post.get('upload_date')
        dt_object = None
        if isinstance(upload_date, datetime):
            dt_object = upload_date
        elif isinstance(upload_date, str):
            try:
                # Handle ISO format with 'T' separator and optional 'Z'
                dt_object = datetime.fromisoformat(upload_date.replace('Z', '+00:00'))
            except ValueError:
                try:
                    # Fallback for date only
                    dt_object = datetime.strptime(upload_date, '%Y-%m-%d')
                except (ValueError, TypeError):
                    pass # Keep dt_object as None
        
        if dt_object is None:
            processed_at_ts = post.get('processed_at')
            dt_object = datetime.fromtimestamp(processed_at_ts, tz=timezone.utc) if processed_at_ts else datetime.now(timezone.utc)

        human_date = dt_object.strftime('%B %d, %Y')
        iso_date = dt_object.isoformat()

        processed_post_data = {
            'title': post.get('title', 'No Title'),
            'description': post.get('description', 'No description available.'),
            'telegram_link': post.get('telegram_link', '#'),
            'human_date': human_date,
            'iso_date': iso_date,
            'thumbnail_url': thumbnail_url,
            'page_url': page_url,
            'absolute_thumbnail_url': absolute_thumbnail_url
        }
        processed_posts.append(processed_post_data)

        seo_data = {
            'title': f"{processed_post_data['title']} | My Awesome Site",
            'description': processed_post_data['description'][:160],
            'canonical_url': f"{SITE_URL}{page_url}",
            'image_url': absolute_thumbnail_url
        }
        post_html = post_template.render(
            seo=seo_data,
            post=processed_post_data,
            now=datetime.now(timezone.utc)
        )
        with open(os.path.join(POSTS_DIR, f"{post_id}.html"), "w", encoding="utf-8") as f:
            f.write(post_html)

    # 5. Generate homepage
    homepage_seo = {'title': "Homepage | My Awesome Site", 'description': "The best place to find awesome content.", 'canonical_url': SITE_URL, 'image_url': f"{SITE_URL}/static/default-social-image.png"}
    index_html = index_template.render(seo=homepage_seo, now=datetime.now(timezone.utc))
    with open(os.path.join(SITE_DIR, "index.html"), "w", encoding="utf-8") as f:
        f.write(index_html)

    # 6. Generate Search page
    search_seo = {'title': "Search | My Awesome Site", 'description': "Search for content on our site.", 'canonical_url': f"{SITE_URL}/search.html", 'image_url': f"{SITE_URL}/static/default-social-image.png"}
    search_html = search_template.render(seo=search_seo, now=datetime.now(timezone.utc))
    with open(os.path.join(SITE_DIR, "search.html"), "w", encoding="utf-8") as f:
        f.write(search_html)

    # 7. Generate supporting files
    generate_robots_txt()
    generate_sitemap(processed_posts)

    # 8. Cleanup template directory
    shutil.rmtree(TEMPLATE_DIR)

    print("Website generation complete with search features!")


if __name__ == '__main__':
    try:
        import jinja2
    except ImportError:
        print("Jinja2 not found. Installing...")
        import subprocess
        import sys
        subprocess.check_call([sys.executable, "-m", "pip", "install", "jinja2"])

    asyncio.run(generate_site())
